# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyTree' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyTree

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'ExpandingMenu'
  pod 'SCLAlertView', '~> 0.8'
  pod 'JGProgressHUD'
  pod 'CropViewController'
  pod 'DropDown'
  pod 'DatePickerDialog'
  pod 'PryntTrimmerView'
  pod 'Loaf'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'ReachabilitySwift', '~> 3'
  pod 'SideMenu'
  pod 'Kingfisher'
  pod 'BmoViewPager', '~> 5.1.0'
end
